-- VHDL Entity ece411.CU.generatedInstance
--
-- Created:
--          by - bhatia9.UNKNOWN (gelib-057-12.ews.illinois.edu)
--          at - 23:04:27 10/23/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY CU IS
   PORT( 
      RESET_L     : IN     std_logic;
      EX_C_Out    : IN     lc3b_word;
      ID_C_Out    : IN     lc3b_word;
      MEM_C_Out   : IN     lc3b_word;
      EX_C_In     : OUT    lc3b_word;
      ID_C_In     : OUT    lc3b_word;
      MEM_C_In    : OUT    lc3b_word;
      WB_C_In     : OUT    lc3b_word;
      IF_C_In     : OUT    lc3b_word;
      clk         : IN     std_logic;
      im_resp_h   : IN     std_logic;
      im_read_l   : OUT    std_logic;
      im_writel_l : OUT    std_logic;
      im_writeh_l : OUT    std_logic
   );

END CU ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF CU IS 
BEGIN


END generatedInstance;
