-- VHDL Entity ece411.CU.interface
--
-- Created:
--          by - bhatia9.UNKNOWN (gelib-057-16.ews.illinois.edu)
--          at - 18:03:53 10/24/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY CU IS
   PORT( 
      EX_C_Out    : IN     lc3b_word;
      ID_C_Out    : IN     lc3b_word;
      MEM_C_Out   : IN     lc3b_word;
      RESET_L     : IN     std_logic;
      clk         : IN     std_logic;
      im_resp_h   : IN     std_logic;
      EX_C_In     : OUT    lc3b_word;
      ID_C_In     : OUT    lc3b_word;
      IF_C_In     : OUT    lc3b_word;
      MEM_C_In    : OUT    lc3b_word;
      WB_C_In     : OUT    lc3b_word;
      im_read_l   : OUT    std_logic;
      im_writeh_l : OUT    std_logic;
      im_writel_l : OUT    std_logic
   );

-- Declarations

END CU ;

--
-- VHDL Architecture ece411.CU.struct
--
-- Created:
--          by - bhatia9.UNKNOWN (gelib-057-16.ews.illinois.edu)
--          at - 18:03:53 10/24/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF CU IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT IF_C_UNIT
   PORT (
      RESET_L   : IN     std_logic ;
      clk       : IN     std_logic ;
      im_resp_h : IN     std_logic ;
      IF_C_In   : OUT    lc3b_word ;
      im_read_l : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : IF_C_UNIT USE ENTITY ece411.IF_C_UNIT;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   IF_GUNIT : IF_C_UNIT
      PORT MAP (
         RESET_L   => RESET_L,
         clk       => clk,
         im_resp_h => im_resp_h,
         IF_C_In   => IF_C_In,
         im_read_l => im_read_l
      );

END struct;
