-- VHDL Entity ece411.CU.interface
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-16.ews.illinois.edu)
--          at - 03:54:15 10/28/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY CU IS
   PORT( 
      EX_C_Out    : IN     lc3b_word;
      ID_C_Out    : IN     lc3b_word;
      MEM_C_Out   : IN     lc3b_word;
      RESET_L     : IN     std_logic;
      clk         : IN     std_logic;
      dm_resp_h   : IN     std_logic;
      im_resp_h   : IN     std_logic;
      instOut     : IN     lc3b_word;
      EX_C_In     : OUT    lc3b_word;
      ID_C_In     : OUT    lc3b_word;
      IF_C_In     : OUT    lc3b_word;
      MEM_C_In    : OUT    lc3b_word;
      WB_C_In     : OUT    lc3b_word;
      dm_read_l   : OUT    std_logic;
      dm_writeh_l : OUT    std_logic;
      dm_writel_l : OUT    std_logic;
      im_read_l   : OUT    std_logic;
      im_writeh_l : OUT    std_logic;
      im_writel_l : OUT    std_logic
   );

-- Declarations

END CU ;

--
-- VHDL Architecture ece411.CU.struct
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-16.ews.illinois.edu)
--          at - 03:54:15 10/28/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF CU IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL ex_c  : lc3b_word;
   SIGNAL mem_c : lc3b_word;
   SIGNAL wb_c  : lc3b_word;

   -- Implicit buffer signal declarations
   SIGNAL im_read_l_internal : std_logic;


   -- Component Declarations
   COMPONENT EX_C_REG
   PORT (
      RESET_L : IN     std_logic ;
      clk     : IN     std_logic ;
      ex_c    : IN     lc3b_word ;
      EX_C_In : OUT    lc3b_word 
   );
   END COMPONENT;
   COMPONENT EX_C_UNIT
   PORT (
      instOut : IN     lc3b_word ;
      ex_c    : OUT    lc3b_word 
   );
   END COMPONENT;
   COMPONENT ID_C_UNIT
   PORT (
      instOut : IN     lc3b_word ;
      ID_C_In : OUT    lc3b_word 
   );
   END COMPONENT;
   COMPONENT IF_C_UNIT
   PORT (
      RESET_L   : IN     std_logic ;
      clk       : IN     std_logic ;
      im_resp_h : IN     std_logic ;
      IF_C_In   : OUT    lc3b_word ;
      im_read_l : INOUT  std_logic 
   );
   END COMPONENT;
   COMPONENT MEM_C_REG
   PORT (
      RESET_L   : IN     std_logic ;
      clk       : IN     std_logic ;
      mem_c     : IN     lc3b_word ;
      MEM_C_In  : OUT    lc3b_word ;
      dm_read_l : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT MEM_C_UNIT
   PORT (
      instOut : IN     lc3b_word ;
      mem_c   : OUT    lc3b_word 
   );
   END COMPONENT;
   COMPONENT WB_C_REG
   PORT (
      RESET_L : IN     std_logic ;
      clk     : IN     std_logic ;
      wb_c    : IN     lc3b_word ;
      WB_C_In : OUT    lc3b_word 
   );
   END COMPONENT;
   COMPONENT WB_C_UNIT
   PORT (
      instOut : IN     lc3b_word ;
      wb_c    : OUT    lc3b_word 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : EX_C_REG USE ENTITY ece411.EX_C_REG;
   FOR ALL : EX_C_UNIT USE ENTITY ece411.EX_C_UNIT;
   FOR ALL : ID_C_UNIT USE ENTITY ece411.ID_C_UNIT;
   FOR ALL : IF_C_UNIT USE ENTITY ece411.IF_C_UNIT;
   FOR ALL : MEM_C_REG USE ENTITY ece411.MEM_C_REG;
   FOR ALL : MEM_C_UNIT USE ENTITY ece411.MEM_C_UNIT;
   FOR ALL : WB_C_REG USE ENTITY ece411.WB_C_REG;
   FOR ALL : WB_C_UNIT USE ENTITY ece411.WB_C_UNIT;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   EX_creg : EX_C_REG
      PORT MAP (
         RESET_L => RESET_L,
         clk     => clk,
         ex_c    => ex_c,
         EX_C_In => EX_C_In
      );
   EX_GUNIT : EX_C_UNIT
      PORT MAP (
         instOut => instOut,
         ex_c    => ex_c
      );
   ID_GUNIT : ID_C_UNIT
      PORT MAP (
         instOut => instOut,
         ID_C_In => ID_C_In
      );
   IF_GUNIT : IF_C_UNIT
      PORT MAP (
         RESET_L   => RESET_L,
         clk       => clk,
         im_resp_h => im_resp_h,
         IF_C_In   => IF_C_In,
         im_read_l => im_read_l_internal
      );
   MEM_creg : MEM_C_REG
      PORT MAP (
         RESET_L   => RESET_L,
         clk       => clk,
         mem_c     => mem_c,
         MEM_C_In  => MEM_C_In,
         dm_read_l => dm_read_l
      );
   MEM_GUNIT : MEM_C_UNIT
      PORT MAP (
         instOut => instOut,
         mem_c   => mem_c
      );
   WB_creg : WB_C_REG
      PORT MAP (
         RESET_L => RESET_L,
         clk     => clk,
         wb_c    => wb_c,
         WB_C_In => WB_C_In
      );
   WB_GUNIT : WB_C_UNIT
      PORT MAP (
         instOut => instOut,
         wb_c    => wb_c
      );

   -- Implicit buffered output assignments
   im_read_l <= im_read_l_internal;

END struct;
