-- VHDL Entity ece411.DataWriteCalc.symbol
--
-- Created:
--          by - bhatia9.UNKNOWN (siebl-0216-08.ews.illinois.edu)
--          at - 22:02:16 11/02/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY DataWriteCalc IS
   PORT( 
      Hit         : IN     std_logic;
      PreHit      : IN     std_logic;
      WaySelect   : IN     std_logic;
      WriteAccess : IN     std_logic;
      clk         : IN     std_logic;
      in_Load     : IN     std_logic;
      DataWrite   : OUT    std_logic;
      DirtyWrite  : OUT    std_logic
   );

-- Declarations

END DataWriteCalc ;

--
-- VHDL Architecture ece411.DataWriteCalc.struct
--
-- Created:
--          by - bhatia9.UNKNOWN (siebl-0216-08.ews.illinois.edu)
--          at - 22:02:16 11/02/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF DataWriteCalc IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL O       : std_logic;
   SIGNAL O2      : std_logic;
   SIGNAL killClk : std_logic;
   SIGNAL o1      : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL DirtyWrite_internal : std_logic;


   -- Component Declarations
   COMPONENT WriteKillClock
   PORT (
      clk     : IN     std_logic ;
      killClk : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT my3NAND
   PORT (
      a : IN     std_logic ;
      b : IN     std_logic ;
      c : IN     std_logic ;
      o : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT myAND
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      O : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT myNOT
   PORT (
      a     : IN     std_logic ;
      a_not : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT myOR
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      O : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : WriteKillClock USE ENTITY ece411.WriteKillClock;
   FOR ALL : my3NAND USE ENTITY ece411.my3NAND;
   FOR ALL : myAND USE ENTITY ece411.myAND;
   FOR ALL : myNOT USE ENTITY ece411.myNOT;
   FOR ALL : myOR USE ENTITY ece411.myOR;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   writeKiller : WriteKillClock
      PORT MAP (
         clk     => clk,
         killClk => killClk
      );
   writeNAND : my3NAND
      PORT MAP (
         a => PreHit,
         b => Hit,
         c => WriteAccess,
         o => o1
      );
   killerAND : myAND
      PORT MAP (
         A => O2,
         B => killClk,
         O => DataWrite
      );
   loadAND : myAND
      PORT MAP (
         A => in_Load,
         B => WaySelect,
         O => O
      );
   U_0 : myNOT
      PORT MAP (
         a     => o1,
         a_not => DirtyWrite_internal
      );
   DWOR : myOR
      PORT MAP (
         A => O,
         B => DirtyWrite_internal,
         O => O2
      );

   -- Implicit buffered output assignments
   DirtyWrite <= DirtyWrite_internal;

END struct;
