-- VHDL Entity ece411.EX_C_REG.generatedInstance
--
-- Created:
--          by - bhatia9.UNKNOWN (gelib-057-16.ews.illinois.edu)
--          at - 23:11:08 10/24/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY EX_C_REG IS
   PORT( 
      EX_C_In : OUT    lc3b_word;
      ex_c    : IN     lc3b_word;
      RESET_L : IN     std_logic;
      clk     : IN     std_logic
   );

END EX_C_REG ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF EX_C_REG IS 
BEGIN


END generatedInstance;
