-- VHDL Entity ece411.EXStage.interface
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-34.ews.illinois.edu)
--          at - 19:20:24 10/21/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY EXStage IS
   PORT( 
      ALUInA   : IN     lc3b_word;
      ALUInB   : IN     lc3b_word;
      EX_C_In  : IN     lc3b_word;
      ALUOut   : OUT    lc3b_word;
      EX_C_Out : OUT    lc3b_word
   );

-- Declarations

END EXStage ;

--
-- VHDL Architecture ece411.EXStage.struct
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-34.ews.illinois.edu)
--          at - 19:20:24 10/21/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;
LIBRARY mp3lib;

ARCHITECTURE struct OF EXStage IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL ALUOP : LC3B_ALUOP;


   -- Component Declarations
   COMPONENT EX_C_Decode
   PORT (
      EX_C_In : IN     lc3b_word ;
      ALUOP   : OUT    LC3B_ALUOP 
   );
   END COMPONENT;
   COMPONENT ALU
   PORT (
      A     : IN     LC3B_WORD ;
      ALUOP : IN     LC3B_ALUOP ;
      B     : IN     LC3B_WORD ;
      F     : OUT    LC3B_WORD 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ALU USE ENTITY mp3lib.ALU;
   FOR ALL : EX_C_Decode USE ENTITY ece411.EX_C_Decode;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   EX_decoder : EX_C_Decode
      PORT MAP (
         EX_C_In => EX_C_In,
         ALUOP   => ALUOP
      );
   EXALU : ALU
      PORT MAP (
         A     => ALUInA,
         ALUOP => ALUOP,
         B     => ALUInB,
         F     => ALUOut
      );

END struct;
