-- VHDL Entity ece411.Hit2InCalc.symbol
--
-- Created:
--          by - bhatia9.UNKNOWN (siebl-0216-08.ews.illinois.edu)
--          at - 22:02:15 11/02/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Hit2InCalc IS
   PORT( 
      PreHit0    : IN     std_logic;
      PreHit1    : IN     std_logic;
      active     : IN     std_logic;
      clk        : IN     std_logic;
      in_IdleHit : IN     std_logic;
      Hit        : OUT    std_logic;
      Miss       : OUT    std_logic
   );

-- Declarations

END Hit2InCalc ;

--
-- VHDL Architecture ece411.Hit2InCalc.struct
--
-- Created:
--          by - bhatia9.UNKNOWN (siebl-0216-08.ews.illinois.edu)
--          at - 22:02:16 11/02/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF Hit2InCalc IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Pre2Hit      : std_logic;
   SIGNAL Pre3Hit      : std_logic;
   SIGNAL PreMiss      : std_logic;
   SIGNAL delayClock   : std_logic;
   SIGNAL noHit        : std_logic;
   SIGNAL uncheckedHit : std_logic;


   -- Component Declarations
   COMPONENT hitClock
   PORT (
      clk        : IN     std_logic ;
      delayClock : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT myAND
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      O : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT myNOT
   PORT (
      a     : IN     std_logic ;
      a_not : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT myOR
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      O : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : hitClock USE ENTITY ece411.hitClock;
   FOR ALL : myAND USE ENTITY ece411.myAND;
   FOR ALL : myNOT USE ENTITY ece411.myNOT;
   FOR ALL : myOR USE ENTITY ece411.myOR;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   ahitClock : hitClock
      PORT MAP (
         delayClock => delayClock,
         clk        => clk
      );
   HitAnd : myAND
      PORT MAP (
         A => uncheckedHit,
         B => delayClock,
         O => Hit
      );
   MissAND : myAND
      PORT MAP (
         A => noHit,
         B => active,
         O => PreMiss
      );
   aHitAND : myAND
      PORT MAP (
         A => active,
         B => Pre2Hit,
         O => Pre3Hit
      );
   idleHitAND : myAND
      PORT MAP (
         A => Pre3Hit,
         B => in_IdleHit,
         O => uncheckedHit
      );
   ihMissAND : myAND
      PORT MAP (
         A => in_IdleHit,
         B => PreMiss,
         O => Miss
      );
   U_1 : myNOT
      PORT MAP (
         a     => Pre2Hit,
         a_not => noHit
      );
   aHitOr : myOR
      PORT MAP (
         A => PreHit0,
         B => PreHit1,
         O => Pre2Hit
      );

END struct;
