-- VHDL Entity ece411.Hit8InCalc.interface
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-19.ews.illinois.edu)
--          at - 12:40:57 12/05/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Hit8InCalc IS
   PORT( 
      PreHit0    : IN     std_logic;
      PreHit1    : IN     std_logic;
      PreHit2    : IN     std_logic;
      PreHit3    : IN     std_logic;
      PreHit4    : IN     std_logic;
      PreHit5    : IN     std_logic;
      PreHit6    : IN     std_logic;
      PreHit7    : IN     std_logic;
      active     : IN     std_logic;
      clk        : IN     std_logic;
      in_idlehit : IN     std_logic;
      Hit        : OUT    std_logic;
      Miss       : OUT    std_logic
   );

-- Declarations

END Hit8InCalc ;

--
-- VHDL Architecture ece411.Hit8InCalc.struct
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-19.ews.illinois.edu)
--          at - 12:40:57 12/05/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF Hit8InCalc IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL B        : std_logic;
   SIGNAL O        : std_logic;
   SIGNAL O1       : std_logic;
   SIGNAL O2       : std_logic;
   SIGNAL a_not    : std_logic;
   SIGNAL preOrOut : std_logic;


   -- Component Declarations
   COMPONENT OR8in
   PORT (
      A     : IN     std_logic ;
      B     : IN     std_logic ;
      C     : IN     std_logic ;
      D     : IN     std_logic ;
      E     : IN     std_logic ;
      F     : IN     std_logic ;
      G     : IN     std_logic ;
      H     : IN     std_logic ;
      OROUT : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT hitClock8
   PORT (
      clk : IN     std_logic ;
      B   : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT myAND
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      O : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT myNOT
   PORT (
      a     : IN     std_logic ;
      a_not : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : OR8in USE ENTITY ece411.OR8in;
   FOR ALL : hitClock8 USE ENTITY ece411.hitClock8;
   FOR ALL : myAND USE ENTITY ece411.myAND;
   FOR ALL : myNOT USE ENTITY ece411.myNOT;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   preOR : OR8in
      PORT MAP (
         A     => PreHit0,
         B     => PreHit1,
         C     => PreHit2,
         D     => PreHit3,
         E     => PreHit4,
         F     => PreHit5,
         G     => PreHit6,
         H     => PreHit7,
         OROUT => preOrOut
      );
   L2hitClock : hitClock8
      PORT MAP (
         clk => clk,
         B   => B
      );
   MissAnd : myAND
      PORT MAP (
         A => active,
         B => a_not,
         O => O2
      );
   aHitAnd : myAND
      PORT MAP (
         A => active,
         B => preOrOut,
         O => O1
      );
   hitAND : myAND
      PORT MAP (
         A => O,
         B => B,
         O => Hit
      );
   idleHitAnd : myAND
      PORT MAP (
         A => in_idlehit,
         B => O1,
         O => O
      );
   ihMissAnd : myAND
      PORT MAP (
         A => in_idlehit,
         B => O2,
         O => Miss
      );
   U_0 : myNOT
      PORT MAP (
         a     => preOrOut,
         a_not => a_not
      );

END struct;
