-- VHDL Entity ece411.hitClock.generatedInstance
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-31.ews.illinois.edu)
--          at - 18:41:43 09/27/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY hitClock IS
   PORT( 
      B : OUT    std_logic
   );

END hitClock ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF hitClock IS 
BEGIN


END generatedInstance;
