-- VHDL Entity ece411.hitClock1.generatedInstance
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-09.ews.illinois.edu)
--          at - 18:55:56 09/28/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY hitClock1 IS
   PORT( 
      delayClock : OUT    std_logic;
      clk        : IN     std_logic
   );

END hitClock1 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF hitClock1 IS 
BEGIN


END generatedInstance;
