-- VHDL Entity ece411.ID_C_UNIT.generatedInstance
--
-- Created:
--          by - bhatia9.UNKNOWN (gelib-057-16.ews.illinois.edu)
--          at - 22:07:36 10/24/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ID_C_UNIT IS
   PORT( 
      instOut : IN     lc3b_word;
      clk     : IN     std_logic;
      RESET_L : IN     std_logic;
      ID_C_In : OUT    lc3b_word
   );

END ID_C_UNIT ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ID_C_UNIT IS 
BEGIN


END generatedInstance;
