-- VHDL Entity ece411.ID_C_Decode.generatedInstance
--
-- Created:
--          by - bhatia9.UNKNOWN (gelib-057-12.ews.illinois.edu)
--          at - 19:40:59 10/23/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ID_C_Decode IS
   PORT( 
      ALUMuxSel : OUT    LC3b_8mux_sel;
      ID_C_In   : IN     lc3b_word
   );

END ID_C_Decode ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ID_C_Decode IS 
BEGIN


END generatedInstance;
