-- VHDL Entity ece411.IDStage.interface
--
-- Created:
--          by - bhatia9.UNKNOWN (gelib-057-14.ews.illinois.edu)
--          at - 01:55:36 10/27/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY IDStage IS
   PORT( 
      ID_C_In  : IN     lc3b_word;
      OutA     : IN     lc3b_word;
      OutB     : IN     lc3b_word;
      instIn   : IN     lc3b_word;
      nextPCin : IN     lc3b_word;
      ALUInA   : OUT    lc3b_word;
      ALUInB   : OUT    lc3b_word;
      ID_C_Out : OUT    lc3b_word;
      RA       : OUT    lc3b_reg;
      RB       : OUT    lc3b_reg;
      instOut  : OUT    lc3b_word;
      newPC    : OUT    lc3b_word
   );

-- Declarations

END IDStage ;

--
-- VHDL Architecture ece411.IDStage.struct
--
-- Created:
--          by - bhatia9.UNKNOWN (gelib-057-14.ews.illinois.edu)
--          at - 01:55:36 10/27/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF IDStage IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL ALUMuxSel : LC3b_8MUX_SEL;


   -- Component Declarations
   COMPONENT ID_C_Decode
   PORT (
      ID_C_In   : IN     lc3b_word ;
      ALUMuxSel : OUT    LC3b_8MUX_SEL 
   );
   END COMPONENT;
   COMPONENT WordMux8
   PORT (
      A   : IN     LC3b_word ;
      B   : IN     LC3b_word ;
      C   : IN     LC3b_word ;
      D   : IN     LC3b_word ;
      E   : IN     LC3b_word ;
      F   : IN     LC3b_word ;
      G   : IN     LC3b_word ;
      H   : IN     LC3b_word ;
      Sel : IN     LC3b_8MUX_SEL ;
      O   : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT Worthless
   PORT (
      In0  : IN     LC3b_word ;
      Out0 : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT regExtractor
   PORT (
      instIn : IN     lc3b_word ;
      RA     : OUT    lc3b_reg ;
      RB     : OUT    lc3b_reg 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ID_C_Decode USE ENTITY ece411.ID_C_Decode;
   FOR ALL : WordMux8 USE ENTITY ece411.WordMux8;
   FOR ALL : Worthless USE ENTITY ece411.Worthless;
   FOR ALL : regExtractor USE ENTITY ece411.regExtractor;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   Decodinator : ID_C_Decode
      PORT MAP (
         ID_C_In   => ID_C_In,
         ALUMuxSel => ALUMuxSel
      );
   ALUMux : WordMux8
      PORT MAP (
         A   => OutB,
         B   => nextPCin,
         C   => nextPCin,
         D   => nextPCin,
         E   => nextPCin,
         F   => nextPCin,
         G   => nextPCin,
         H   => nextPCin,
         Sel => ALUMuxSel,
         O   => ALUInB
      );
   terriBAD : Worthless
      PORT MAP (
         In0  => OutA,
         Out0 => ALUInA
      );
   terriBAD1 : Worthless
      PORT MAP (
         In0  => instIn,
         Out0 => instOut
      );
   Extractinator : regExtractor
      PORT MAP (
         instIn => instIn,
         RA     => RA,
         RB     => RB
      );

END struct;
