-- VHDL Entity ece411.InstrRipper.generatedInstance
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-16.ews.illinois.edu)
--          at - 00:08:50 10/28/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY InstrRipper IS
   PORT( 
      instIn  : IN     lc3b_word;
      Instr5  : OUT    lc3b_imm5;
      Instr9  : OUT    lc3b_offset9;
      Instr11 : OUT    lc3b_offset11;
      Instr6  : OUT    lc3b_index6
   );

END InstrRipper ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF InstrRipper IS 
BEGIN


END generatedInstance;
