-- VHDL Entity ece411.L1_Cache.symbol
--
-- Created:
--          by - bhatia9.UNKNOWN (gelib-057-12.ews.illinois.edu)
--          at - 21:51:47 10/23/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY L1_Cache IS
   PORT( 
      AddressIn      : IN     lc3b_word;
      ArbiterControl : IN     std_logic;
      DataIn         : IN     lc3b_word;
      RESET_L        : IN     std_logic;
      clk            : IN     std_logic;
      DataOut        : OUT    lc3b_word;
      Hit            : OUT    std_logic;
      Miss           : OUT    std_logic
   );

-- Declarations

END L1_Cache ;

--
-- VHDL Architecture ece411.L1_Cache.struct
--
-- Created:
--          by - bhatia9.UNKNOWN (gelib-057-12.ews.illinois.edu)
--          at - 21:51:47 10/23/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF L1_Cache IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- Instance port mappings.

END struct;
