-- VHDL Entity ece411.L2CacheUnit.symbol
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-19.ews.illinois.edu)
--          at - 12:52:31 12/05/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY L2CacheUnit IS
   PORT( 
      ADDRESS   : IN     LC3b_word;
      DATAOUT   : IN     LC3b_oword;
      MREAD_L   : IN     std_logic;
      MWRITE_L  : IN     std_logic;
      RESET_L   : IN     std_logic;
      clk       : IN     std_logic;
      pmdatain  : IN     lc3b_oword;
      pmresp_h  : IN     std_logic;
      DATAIN    : OUT    LC3b_oword;
      MRESP_H   : OUT    std_logic;
      pmaddress : OUT    LC3b_word;
      pmdataout : OUT    lc3b_oword;
      pmread_l  : OUT    std_logic;
      pmwrite_l : OUT    std_logic
   );

-- Declarations

END L2CacheUnit ;

--
-- VHDL Architecture ece411.L2CacheUnit.struct
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-19.ews.illinois.edu)
--          at - 12:52:31 12/05/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF L2CacheUnit IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Dirty      : std_logic;
   SIGNAL Hit        : std_logic;
   SIGNAL Miss       : std_logic;
   SIGNAL in_IdleHit : std_logic;
   SIGNAL in_Load    : std_logic;


   -- Component Declarations
   COMPONENT Cache_Controller
   PORT (
      Dirty      : IN     std_logic ;
      Hit        : IN     std_logic ;
      Miss       : IN     std_logic ;
      RESET_L    : IN     std_logic ;
      clk        : IN     std_logic ;
      pmresp_h   : IN     std_logic ;
      in_IdleHit : OUT    std_logic ;
      in_Load    : OUT    std_logic ;
      pmread_l   : OUT    std_logic ;
      pmwrite_l  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT L2Cache
   PORT (
      ADDRESS    : IN     LC3b_word ;
      DATAOUT    : IN     LC3b_oword ;
      MREAD_L    : IN     std_logic ;
      MWRITE_L   : IN     std_logic ;
      RESET_L    : IN     std_logic ;
      clk        : IN     std_logic ;
      in_Load    : IN     std_logic ;
      in_idlehit : IN     std_logic ;
      pmdatain   : IN     lc3b_oword ;
      DATAIN     : OUT    LC3b_oword ;
      Dirty      : OUT    std_logic ;
      Hit        : OUT    std_logic ;
      MRESP_H    : OUT    std_logic ;
      Miss       : OUT    std_logic ;
      pmaddress  : OUT    LC3b_word ;
      pmdataout  : OUT    lc3b_oword 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Cache_Controller USE ENTITY ece411.Cache_Controller;
   FOR ALL : L2Cache USE ENTITY ece411.L2Cache;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   L2CacheCont : Cache_Controller
      PORT MAP (
         Dirty      => Dirty,
         Hit        => Hit,
         Miss       => Miss,
         RESET_L    => RESET_L,
         clk        => clk,
         pmresp_h   => pmresp_h,
         in_IdleHit => in_IdleHit,
         in_Load    => in_Load,
         pmread_l   => pmread_l,
         pmwrite_l  => pmwrite_l
      );
   DataPath : L2Cache
      PORT MAP (
         ADDRESS    => ADDRESS,
         DATAOUT    => DATAOUT,
         MREAD_L    => MREAD_L,
         MWRITE_L   => MWRITE_L,
         RESET_L    => RESET_L,
         clk        => clk,
         in_Load    => in_Load,
         in_idlehit => in_IdleHit,
         pmdatain   => pmdatain,
         DATAIN     => DATAIN,
         Dirty      => Dirty,
         Hit        => Hit,
         MRESP_H    => MRESP_H,
         Miss       => Miss,
         pmaddress  => pmaddress,
         pmdataout  => pmdataout
      );

END struct;
