-- VHDL Entity ece411.LRUTruth.interface
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-19.ews.illinois.edu)
--          at - 07:02:23 12/05/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY LRUTruth IS
   PORT( 
      Hit     : IN     std_logic;
      PreHit0 : IN     std_logic;
      PreHit1 : IN     std_logic;
      PreHit2 : IN     std_logic;
      PreHit3 : IN     std_logic;
      PreHit4 : IN     std_logic;
      PreHit5 : IN     std_logic;
      PreHit6 : IN     std_logic;
      PreHit7 : IN     std_logic;
      RESET_L : IN     std_logic;
      index   : IN     lc3b_c_index;
      LRUOut  : OUT    lc3b_8mux_sel
   );

-- Declarations

END LRUTruth ;

--
-- VHDL Architecture ece411.LRUTruth.struct
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-19.ews.illinois.edu)
--          at - 07:02:23 12/05/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF LRUTruth IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL LU       : lc3b_8mux_sel;
   SIGNAL LUMuxSel : lc3b_8mux_sel;
   SIGNAL LUout0   : lc3b_8mux_sel;
   SIGNAL LUout1   : lc3b_8mux_sel;
   SIGNAL LUout2   : lc3b_8mux_sel;
   SIGNAL LUout3   : lc3b_8mux_sel;
   SIGNAL LUout4   : lc3b_8mux_sel;
   SIGNAL LUout5   : lc3b_8mux_sel;
   SIGNAL LUout6   : lc3b_8mux_sel;
   SIGNAL LUout7   : lc3b_8mux_sel;
   SIGNAL win0     : std_logic;
   SIGNAL win1     : std_logic;
   SIGNAL win2     : std_logic;
   SIGNAL win3     : std_logic;
   SIGNAL win4     : std_logic;
   SIGNAL win5     : std_logic;
   SIGNAL win6     : std_logic;
   SIGNAL win7     : std_logic;


   -- Component Declarations
   COMPONENT Encoder8in
   PORT (
      PreHit0 : IN     std_logic ;
      PreHit1 : IN     std_logic ;
      PreHit2 : IN     std_logic ;
      PreHit3 : IN     std_logic ;
      PreHit4 : IN     std_logic ;
      PreHit5 : IN     std_logic ;
      PreHit6 : IN     std_logic ;
      PreHit7 : IN     std_logic ;
      dataSel : OUT    lc3b_8MUX_Sel 
   );
   END COMPONENT;
   COMPONENT LUnit
   PORT (
      LU        : IN     lc3b_8mux_sel ;
      RESET_L   : IN     std_logic ;
      hit       : IN     std_logic ;
      hitSelect : IN     STD_LOGIC ;
      index     : IN     lc3b_c_index ;
      LUout     : OUT    lc3b_8mux_sel ;
      winner    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Mux3bit8
   PORT (
      a0  : IN     lc3b_8mux_sel ;
      a1  : IN     lc3b_8mux_sel ;
      a2  : IN     lc3b_8mux_sel ;
      a3  : IN     lc3b_8mux_sel ;
      a4  : IN     lc3b_8mux_sel ;
      a5  : IN     lc3b_8mux_sel ;
      a6  : IN     lc3b_8mux_sel ;
      a7  : IN     lc3b_8mux_sel ;
      sel : IN     lc3b_8mux_sel ;
      O   : OUT    lc3b_8mux_sel 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Encoder8in USE ENTITY ece411.Encoder8in;
   FOR ALL : LUnit USE ENTITY ece411.LUnit;
   FOR ALL : Mux3bit8 USE ENTITY ece411.Mux3bit8;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   LRUEncode : Encoder8in
      PORT MAP (
         PreHit0 => win0,
         PreHit1 => win1,
         PreHit2 => win2,
         PreHit3 => win3,
         PreHit4 => win4,
         PreHit5 => win5,
         PreHit6 => win6,
         PreHit7 => win7,
         dataSel => LRUOut
      );
   LUSelGen : Encoder8in
      PORT MAP (
         PreHit0 => PreHit0,
         PreHit1 => PreHit1,
         PreHit2 => PreHit2,
         PreHit3 => PreHit3,
         PreHit4 => PreHit4,
         PreHit5 => PreHit5,
         PreHit6 => PreHit6,
         PreHit7 => PreHit7,
         dataSel => LUMuxSel
      );
   unit0 : LUnit
      PORT MAP (
         LU        => LU,
         RESET_L   => RESET_L,
         hit       => Hit,
         hitSelect => PreHit0,
         index     => index,
         LUout     => LUout0,
         winner    => win0
      );
   unit1 : LUnit
      PORT MAP (
         LU        => LU,
         RESET_L   => RESET_L,
         hit       => Hit,
         hitSelect => PreHit1,
         index     => index,
         LUout     => LUout1,
         winner    => win1
      );
   unit2 : LUnit
      PORT MAP (
         LU        => LU,
         RESET_L   => RESET_L,
         hit       => Hit,
         hitSelect => PreHit2,
         index     => index,
         LUout     => LUout2,
         winner    => win2
      );
   unit3 : LUnit
      PORT MAP (
         LU        => LU,
         RESET_L   => RESET_L,
         hit       => Hit,
         hitSelect => PreHit3,
         index     => index,
         LUout     => LUout3,
         winner    => win3
      );
   unit4 : LUnit
      PORT MAP (
         LU        => LU,
         RESET_L   => RESET_L,
         hit       => Hit,
         hitSelect => PreHit4,
         index     => index,
         LUout     => LUout4,
         winner    => win4
      );
   unit5 : LUnit
      PORT MAP (
         LU        => LU,
         RESET_L   => RESET_L,
         hit       => Hit,
         hitSelect => PreHit5,
         index     => index,
         LUout     => LUout5,
         winner    => win5
      );
   unit6 : LUnit
      PORT MAP (
         LU        => LU,
         RESET_L   => RESET_L,
         hit       => Hit,
         hitSelect => PreHit6,
         index     => index,
         LUout     => LUout6,
         winner    => win6
      );
   unit7 : LUnit
      PORT MAP (
         LU        => LU,
         RESET_L   => RESET_L,
         hit       => Hit,
         hitSelect => PreHit7,
         index     => index,
         LUout     => LUout7,
         winner    => win7
      );
   LUMux : Mux3bit8
      PORT MAP (
         a0  => LUout0,
         a1  => LUout1,
         a2  => LUout2,
         a3  => LUout3,
         a4  => LUout4,
         a5  => LUout5,
         a6  => LUout6,
         a7  => LUout7,
         sel => LUMuxSel,
         O   => LU
      );

END struct;
