-- VHDL Entity ece411.LUnit.symbol
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-19.ews.illinois.edu)
--          at - 06:44:56 12/05/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY LUnit IS
   PORT( 
      LU        : IN     lc3b_8mux_sel;
      RESET_L   : IN     std_logic;
      hit       : IN     std_logic;
      hitSelect : IN     STD_LOGIC;
      index     : IN     lc3b_c_index;
      LUout     : OUT    lc3b_8mux_sel;
      winner    : OUT    std_logic
   );

-- Declarations

END LUnit ;

--
-- VHDL Architecture ece411.LUnit.struct
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-19.ews.illinois.edu)
--          at - 06:44:56 12/05/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;
LIBRARY mp3lib;

ARCHITECTURE struct OF LUnit IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F1       : STD_LOGIC_VECTOR(2 DOWNTO 0);
   SIGNAL luPlus1  : lc3b_8mux_sel;
   SIGNAL luSel    : std_logic;
   SIGNAL newLUin  : STD_LOGIC_VECTOR(2 DOWNTO 0);
   SIGNAL zerobits : lc3b_8mux_sel;

   -- Implicit buffer signal declarations
   SIGNAL LUout_internal : lc3b_8mux_sel;


   -- Component Declarations
   COMPONENT LRUReg3bit8
   PORT (
      RESET_L : IN     std_logic ;
      hit     : IN     std_logic ;
      index   : IN     lc3b_c_index ;
      newLU   : IN     lc3b_8mux_sel ;
      LUout   : OUT    lc3b_8mux_sel 
   );
   END COMPONENT;
   COMPONENT LRUplusone
   PORT (
      LRUin      : IN     lc3b_8mux_sel ;
      LRUplusOne : OUT    lc3b_8mux_sel 
   );
   END COMPONENT;
   COMPONENT compare3bits
   PORT (
      LU      : IN     lc3b_8mux_sel ;
      LUother : IN     lc3b_8mux_sel ;
      result  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT equals7
   PORT (
      LU     : IN     lc3b_8mux_sel ;
      equals : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT zero
   PORT (
      zero : OUT    lc3b_8mux_sel 
   );
   END COMPONENT;
   COMPONENT MUX2_3
   PORT (
      A   : IN     STD_LOGIC_VECTOR (2 DOWNTO 0);
      B   : IN     STD_LOGIC_VECTOR (2 DOWNTO 0);
      SEL : IN     STD_LOGIC ;
      F   : OUT    STD_LOGIC_VECTOR (2 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : LRUReg3bit8 USE ENTITY ece411.LRUReg3bit8;
   FOR ALL : LRUplusone USE ENTITY ece411.LRUplusone;
   FOR ALL : MUX2_3 USE ENTITY mp3lib.MUX2_3;
   FOR ALL : compare3bits USE ENTITY ece411.compare3bits;
   FOR ALL : equals7 USE ENTITY ece411.equals7;
   FOR ALL : zero USE ENTITY ece411.zero;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   wayLRUReg : LRUReg3bit8
      PORT MAP (
         RESET_L => RESET_L,
         hit     => hit,
         index   => index,
         newLU   => newLUin,
         LUout   => LUout_internal
      );
   plus1 : LRUplusone
      PORT MAP (
         LRUin      => LUout_internal,
         LRUplusOne => luPlus1
      );
   comparring : compare3bits
      PORT MAP (
         LU      => LU,
         LUother => LUout_internal,
         result  => luSel
      );
   is7 : equals7
      PORT MAP (
         LU     => LUout_internal,
         equals => winner
      );
   U_0 : zero
      PORT MAP (
         zero => zerobits
      );
   newLUMux : MUX2_3
      PORT MAP (
         A   => LUout_internal,
         B   => luPlus1,
         SEL => luSel,
         F   => F1
      );
   winMux : MUX2_3
      PORT MAP (
         A   => F1,
         B   => zerobits,
         SEL => hitSelect,
         F   => newLUin
      );

   -- Implicit buffered output assignments
   LUout <= LUout_internal;

END struct;
