-- VHDL Entity ece411.Magmem.generatedInstance
--
-- Created:
--          by - bhatia9.UNKNOWN (siebl-0216-10.ews.illinois.edu)
--          at - 23:40:09 10/28/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Magmem IS
   PORT( 
      im_read_l    : IN     std_logic;
      im_writel_l  : IN     std_logic;
      im_writeh_l  : IN     std_logic;
      dm_read_l    : IN     std_logic;
      dm_writeh_l  : IN     std_logic;
      dm_writel_l  : IN     std_logic;
      clk          : IN     std_logic;
      RESET_L      : IN     std_logic;
      im_resp_h    : OUT    std_logic;
      dm_resp_h    : OUT    std_logic;
      DataAddr     : IN     lc3b_word;
      MEMWriteData : IN     lc3b_word;
      PCinstAddr   : IN     lc3b_word;
      DataMemIn    : OUT    lc3b_word;
      InstMemIn    : OUT    lc3b_word
   );

END Magmem ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Magmem IS 
BEGIN


END generatedInstance;
