-- VHDL Entity ece411.MEM_C_UNIT2.generatedInstance
--
-- Created:
--          by - bhatia9.UNKNOWN (siebl-0216-13.ews.illinois.edu)
--          at - 21:02:18 12/03/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY MEM_C_UNIT2 IS
   PORT( 
      instOut : IN     lc3b_word;
      mem_c2  : OUT    lc3b_word
   );

END MEM_C_UNIT2 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF MEM_C_UNIT2 IS 
BEGIN


END generatedInstance;
