-- VHDL Entity ece411.MEM_C_UNIT.generatedInstance
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-16.ews.illinois.edu)
--          at - 02:29:08 10/28/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY MEM_C_UNIT IS
   PORT( 
      mem_c   : OUT    lc3b_word;
      instOut : IN     lc3b_word
   );

END MEM_C_UNIT ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF MEM_C_UNIT IS 
BEGIN


END generatedInstance;
