-- VHDL Entity ece411.Memory.interface
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-26.ews.illinois.edu)
--          at - 15:45:36 10/05/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Memory IS
   PORT( 
      ADDRESS   : IN     LC3b_word;
      DATAOUT   : IN     LC3b_word;
      MREAD_L   : IN     std_logic;
      MWRITEH_L : IN     std_logic;
      MWRITEL_L : IN     std_logic;
      RESET_L   : IN     std_logic;
      clk       : IN     std_logic;
      DATAIN    : OUT    LC3b_word;
      MRESP_H   : OUT    std_logic
   );

-- Declarations

END Memory ;

--
-- VHDL Architecture ece411.Memory.struct
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-26.ews.illinois.edu)
--          at - 15:45:36 10/05/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF Memory IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Dirty      : std_logic;
   SIGNAL Hit        : std_logic;
   SIGNAL Miss       : std_logic;
   SIGNAL in_IdleHit : std_logic;
   SIGNAL in_Load    : std_logic;
   SIGNAL pmaddress  : LC3b_word;
   SIGNAL pmdatain   : lc3b_oword;
   SIGNAL pmdataout  : lc3b_oword;
   SIGNAL pmread_l   : std_logic;
   SIGNAL pmresp_h   : std_logic;
   SIGNAL pmwrite_l  : std_logic;


   -- Component Declarations
   COMPONENT Cache_Controller
   PORT (
      Dirty      : IN     std_logic ;
      Hit        : IN     std_logic ;
      Miss       : IN     std_logic ;
      RESET_L    : IN     std_logic ;
      clk        : IN     std_logic ;
      pmresp_h   : IN     std_logic ;
      in_IdleHit : OUT    std_logic ;
      in_Load    : OUT    std_logic ;
      pmread_l   : OUT    std_logic ;
      pmwrite_l  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Cache_Datapath
   PORT (
      ADDRESS    : IN     LC3b_word ;
      DATAOUT    : IN     LC3b_word ;
      MREAD_L    : IN     std_logic ;
      MWRITEH_L  : IN     std_logic ;
      MWRITEL_L  : IN     std_logic ;
      RESET_L    : IN     std_logic ;
      clk        : IN     std_logic ;
      in_IdleHit : IN     std_logic ;
      in_Load    : IN     std_logic ;
      pmdatain   : IN     lc3b_oword ;
      DATAIN     : OUT    LC3b_word ;
      Dirty      : OUT    std_logic ;
      Hit        : OUT    std_logic ;
      MRESP_H    : OUT    std_logic ;
      Miss       : OUT    std_logic ;
      pmaddress  : OUT    LC3b_word ;
      pmdataout  : OUT    lc3b_oword 
   );
   END COMPONENT;
   COMPONENT Physical_Memory
   PORT (
      RESET_L   : IN     std_logic ;
      clk       : IN     std_logic ;
      pmaddress : IN     LC3b_word ;
      pmdataout : IN     lc3b_oword ;
      pmread_l  : IN     std_logic ;
      pmwrite_l : IN     std_logic ;
      pmdatain  : OUT    lc3b_oword ;
      pmresp_h  : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Cache_Controller USE ENTITY ece411.Cache_Controller;
   FOR ALL : Cache_Datapath USE ENTITY ece411.Cache_Datapath;
   FOR ALL : Physical_Memory USE ENTITY ece411.Physical_Memory;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   Cache_Cont : Cache_Controller
      PORT MAP (
         Dirty      => Dirty,
         Hit        => Hit,
         Miss       => Miss,
         RESET_L    => RESET_L,
         clk        => clk,
         pmresp_h   => pmresp_h,
         in_IdleHit => in_IdleHit,
         in_Load    => in_Load,
         pmread_l   => pmread_l,
         pmwrite_l  => pmwrite_l
      );
   Cache_DP : Cache_Datapath
      PORT MAP (
         ADDRESS    => ADDRESS,
         DATAOUT    => DATAOUT,
         MREAD_L    => MREAD_L,
         MWRITEH_L  => MWRITEH_L,
         MWRITEL_L  => MWRITEL_L,
         RESET_L    => RESET_L,
         clk        => clk,
         in_IdleHit => in_IdleHit,
         in_Load    => in_Load,
         pmdatain   => pmdatain,
         DATAIN     => DATAIN,
         Dirty      => Dirty,
         Hit        => Hit,
         MRESP_H    => MRESP_H,
         Miss       => Miss,
         pmaddress  => pmaddress,
         pmdataout  => pmdataout
      );
   PDRAM : Physical_Memory
      PORT MAP (
         RESET_L   => RESET_L,
         clk       => clk,
         pmaddress => pmaddress,
         pmdataout => pmdataout,
         pmread_l  => pmread_l,
         pmwrite_l => pmwrite_l,
         pmdatain  => pmdatain,
         pmresp_h  => pmresp_h
      );

END struct;
