-- VHDL Entity ece411.MemoryUnit.interface
--
-- Created:
--          by - bhatia9.UNKNOWN (gelib-057-12.ews.illinois.edu)
--          at - 22:18:05 10/23/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY MemoryUnit IS
-- Declarations

END MemoryUnit ;

--
-- VHDL Architecture ece411.MemoryUnit.struct
--
-- Created:
--          by - bhatia9.UNKNOWN (gelib-057-12.ews.illinois.edu)
--          at - 22:18:05 10/23/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF MemoryUnit IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL ArbiterControl  : std_logic;
   SIGNAL ArbiterControl1 : std_logic;


   -- Component Declarations
   COMPONENT Arbiter
   PORT (
      ArbiterControl  : OUT    std_logic;
      ArbiterControl1 : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT DRAM16_DP
   PORT (
      CLK         : IN     STD_LOGIC;
      D_ADDRESS   : IN     LC3B_WORD;
      D_DATAOUT   : IN     LC3B_WORD;
      D_MREAD_L   : IN     STD_LOGIC;
      D_MWRITEH_L : IN     STD_LOGIC;
      D_MWRITEL_L : IN     STD_LOGIC;
      I_ADDRESS   : IN     LC3B_WORD;
      I_MREAD_L   : IN     STD_LOGIC;
      RESET_L     : IN     STD_LOGIC;
      D_DATAIN    : OUT    LC3B_WORD;
      D_MRESP_H   : OUT    STD_LOGIC;
      I_DATAIN    : OUT    LC3B_WORD;
      I_MRESP_H   : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT L1_Cache
   PORT (
      AddressIn      : IN     lc3b_word ;
      ArbiterControl : IN     std_logic ;
      DataIn         : IN     lc3b_word ;
      RESET_L        : IN     std_logic ;
      clk            : IN     std_logic ;
      DataOut        : OUT    lc3b_word ;
      Hit            : OUT    std_logic ;
      Miss           : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT L2_Cache
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Arbiter USE ENTITY ece411.Arbiter;
   FOR ALL : DRAM16_DP USE ENTITY ece411.DRAM16_DP;
   FOR ALL : L1_Cache USE ENTITY ece411.L1_Cache;
   FOR ALL : L2_Cache USE ENTITY ece411.L2_Cache;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   TheArbiter : Arbiter
      PORT MAP (
         ArbiterControl  => ArbiterControl,
         ArbiterControl1 => ArbiterControl1
      );
   Physical_Mem : DRAM16_DP
      PORT MAP (
         RESET_L     => RESET_L,
         CLK         => RESET_L,
         I_MREAD_L   => RESET_L,
         I_ADDRESS   => RESET_L,
         I_MRESP_H   => OPEN,
         I_DATAIN    => OPEN,
         D_MREAD_L   => RESET_L,
         D_MWRITEH_L => RESET_L,
         D_MWRITEL_L => RESET_L,
         D_ADDRESS   => RESET_L,
         D_DATAOUT   => RESET_L,
         D_DATAIN    => OPEN,
         D_MRESP_H   => OPEN
      );
   Data_Mem : L1_Cache
      PORT MAP (
         AddressIn      => DataAddr,
         ArbiterControl => ArbiterControl1,
         DataIn         => MEMWriteData,
         RESET_L        => RESET_L,
         clk            => clk,
         DataOut        => DataMemIn,
         Hit            => OPEN,
         Miss           => OPEN
      );
   Inst_Mem : L1_Cache
      PORT MAP (
         AddressIn      => PCinstAddr,
         ArbiterControl => ArbiterControl,
         DataIn         => InstDataIn,
         RESET_L        => RESET_L,
         clk            => clk,
         DataOut        => InstMemIn,
         Hit            => OPEN,
         Miss           => OPEN
      );
   L2_8way_Cache : L2_Cache;

END struct;
