-- VHDL Entity ece411.MEMStage.interface
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-16.ews.illinois.edu)
--          at - 21:45:26 10/27/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY MEMStage IS
   PORT( 
      ALUresult    : IN     lc3b_word;
      DataMemIn    : IN     lc3b_word;
      MEM_C_In     : IN     lc3b_word;
      SrcIn        : IN     lc3b_word;
      DataAddr     : OUT    lc3b_word;
      MEMDataOut   : OUT    lc3b_word;
      MEMWriteData : OUT    lc3b_word;
      MEM_C_Out    : OUT    lc3b_word
   );

-- Declarations

END MEMStage ;

--
-- VHDL Architecture ece411.MEMStage.struct
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-16.ews.illinois.edu)
--          at - 21:45:26 10/27/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF MEMStage IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT Worthless
   PORT (
      In0  : IN     LC3b_word ;
      Out0 : OUT    LC3b_word 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Worthless USE ENTITY ece411.Worthless;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   Chillin : Worthless
      PORT MAP (
         In0  => DataMemIn,
         Out0 => MEMDataOut
      );
   Just : Worthless
      PORT MAP (
         In0  => ALUresult,
         Out0 => DataAddr
      );
   Man : Worthless
      PORT MAP (
         In0  => SrcIn,
         Out0 => MEMWriteData
      );

END struct;
