-- VHDL Entity ece411.mp2_CPU.symbol
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-26.ews.illinois.edu)
--          at - 15:45:36 10/05/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY mp2_CPU IS
   PORT( 
      RESET_L : IN     std_logic;
      START_H : IN     std_logic
   );

-- Declarations

END mp2_CPU ;

--
-- VHDL Architecture ece411.mp2_CPU.struct
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-26.ews.illinois.edu)
--          at - 15:45:37 10/05/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF mp2_CPU IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL ADDRESS    : LC3b_word;
   SIGNAL ADDR_0     : std_logic;
   SIGNAL ALUMuxSel  : LC3b_8Mux_Sel;
   SIGNAL ALUop      : LC3b_aluop;
   SIGNAL ByteExtSel : std_logic;
   SIGNAL CheckN     : std_logic;
   SIGNAL CheckP     : std_logic;
   SIGNAL CheckZ     : std_logic;
   SIGNAL DATAIN     : LC3b_word;
   SIGNAL DATAOUT    : LC3b_word;
   SIGNAL IMMEDIATE  : std_logic;
   SIGNAL JSRR       : std_logic;
   SIGNAL LoadIR     : std_logic;
   SIGNAL LoadMDR    : std_logic;
   SIGNAL LoadMar    : std_logic;
   SIGNAL LoadNZP    : std_logic;
   SIGNAL LoadPC     : std_logic;
   SIGNAL MARMuxSel  : LC3b_4Mux_Sel;
   SIGNAL MDRMuxSel  : std_logic;
   SIGNAL MREAD_L    : std_logic;
   SIGNAL MRESP_H    : std_logic;
   SIGNAL MWRITEH_L  : std_logic;
   SIGNAL MWRITEL_L  : std_logic;
   SIGNAL Opcode     : LC3b_opcode;
   SIGNAL PCMuxSel   : LC3b_8Mux_Sel;
   SIGNAL R7Sel_H    : std_logic;
   SIGNAL RFMuxSel   : LC3b_4Mux_Sel;
   SIGNAL RegWrite   : std_logic;
   SIGNAL SHIFTop    : lc3b_shftop;
   SIGNAL StoreSR    : std_logic;
   SIGNAL clk        : std_logic := '0';
   SIGNAL n          : std_logic;
   SIGNAL p          : std_logic;
   SIGNAL z          : std_logic;


   -- Component Declarations
   COMPONENT CLKgen
   PORT (
      clk : INOUT  std_logic  := '0'
   );
   END COMPONENT;
   COMPONENT Control
   PORT (
      ADDR_0     : IN     std_logic ;
      CheckN     : IN     std_logic ;
      CheckP     : IN     std_logic ;
      CheckZ     : IN     std_logic ;
      IMMEDIATE  : IN     std_logic ;
      JSRR       : IN     std_logic ;
      MRESP_H    : IN     std_logic ;
      Opcode     : IN     LC3b_opcode ;
      RESET_L    : IN     std_logic ;
      SHIFTop    : IN     lc3b_shftop ;
      START_H    : IN     std_logic ;
      clk        : IN     std_logic ;
      n          : IN     std_logic ;
      p          : IN     std_logic ;
      z          : IN     std_logic ;
      ALUMuxSel  : OUT    LC3b_8Mux_Sel ;
      ALUop      : OUT    LC3b_aluop ;
      ByteExtSel : OUT    std_logic ;
      LoadIR     : OUT    std_logic ;
      LoadMDR    : OUT    std_logic ;
      LoadMar    : OUT    std_logic ;
      LoadNZP    : OUT    std_logic ;
      LoadPC     : OUT    std_logic ;
      MARMuxSel  : OUT    LC3b_4Mux_Sel ;
      MDRMuxSel  : OUT    std_logic ;
      MREAD_L    : OUT    std_logic ;
      MWRITEH_L  : OUT    std_logic ;
      MWRITEL_L  : OUT    std_logic ;
      PCMuxSel   : OUT    LC3b_8Mux_Sel ;
      R7Sel_H    : OUT    std_logic ;
      RFMuxSel   : OUT    LC3b_4Mux_Sel ;
      RegWrite   : OUT    std_logic ;
      StoreSR    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT DRAMAuditor
   PORT (
      ADDRESS   : IN     LC3b_word;
      MREAD_L   : IN     std_logic;
      MWRITEH_L : IN     std_logic;
      MWRITEL_L : IN     std_logic;
      RESET_L   : IN     std_logic
   );
   END COMPONENT;
   COMPONENT Datapath
   PORT (
      ALUMuxSel  : IN     LC3b_8Mux_Sel ;
      ALUop      : IN     LC3b_aluop ;
      ByteExtSel : IN     std_logic ;
      DATAIN     : IN     LC3b_word ;
      LoadIR     : IN     std_logic ;
      LoadMDR    : IN     std_logic ;
      LoadMar    : IN     std_logic ;
      LoadNZP    : IN     std_logic ;
      LoadPC     : IN     std_logic ;
      MARMuxSel  : IN     LC3b_4Mux_Sel ;
      MDRMuxSel  : IN     std_logic ;
      PCMuxSel   : IN     LC3b_8Mux_Sel ;
      R7Sel_H    : IN     std_logic ;
      RESET_L    : IN     std_logic ;
      RFMuxSel   : IN     LC3b_4Mux_Sel ;
      RegWrite   : IN     std_logic ;
      StoreSR    : IN     std_logic ;
      clk        : IN     std_logic ;
      ADDRESS    : OUT    LC3b_word ;
      ADDR_0     : OUT    std_logic ;
      CheckN     : OUT    std_logic ;
      CheckP     : OUT    std_logic ;
      CheckZ     : OUT    std_logic ;
      DATAOUT    : OUT    LC3b_word ;
      IMMEDIATE  : OUT    std_logic ;
      JSRR       : OUT    std_logic ;
      Opcode     : OUT    LC3b_opcode ;
      SHIFTop    : OUT    lc3b_shftop ;
      n          : OUT    std_logic ;
      p          : OUT    std_logic ;
      z          : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Memory
   PORT (
      ADDRESS   : IN     LC3b_word ;
      DATAOUT   : IN     LC3b_word ;
      MREAD_L   : IN     std_logic ;
      MWRITEH_L : IN     std_logic ;
      MWRITEL_L : IN     std_logic ;
      RESET_L   : IN     std_logic ;
      clk       : IN     std_logic ;
      DATAIN    : OUT    LC3b_word ;
      MRESP_H   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : CLKgen USE ENTITY ece411.CLKgen;
   FOR ALL : Control USE ENTITY ece411.Control;
   FOR ALL : DRAMAuditor USE ENTITY ece411.DRAMAuditor;
   FOR ALL : Datapath USE ENTITY ece411.Datapath;
   FOR ALL : Memory USE ENTITY ece411.Memory;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   I0 : CLKgen
      PORT MAP (
         clk => clk
      );
   ControlUnit : Control
      PORT MAP (
         ADDR_0     => ADDR_0,
         CheckN     => CheckN,
         CheckP     => CheckP,
         CheckZ     => CheckZ,
         IMMEDIATE  => IMMEDIATE,
         JSRR       => JSRR,
         MRESP_H    => MRESP_H,
         Opcode     => Opcode,
         RESET_L    => RESET_L,
         SHIFTop    => SHIFTop,
         START_H    => START_H,
         clk        => clk,
         n          => n,
         p          => p,
         z          => z,
         ALUMuxSel  => ALUMuxSel,
         ALUop      => ALUop,
         ByteExtSel => ByteExtSel,
         LoadIR     => LoadIR,
         LoadMDR    => LoadMDR,
         LoadMar    => LoadMar,
         LoadNZP    => LoadNZP,
         LoadPC     => LoadPC,
         MARMuxSel  => MARMuxSel,
         MDRMuxSel  => MDRMuxSel,
         MREAD_L    => MREAD_L,
         MWRITEH_L  => MWRITEH_L,
         MWRITEL_L  => MWRITEL_L,
         PCMuxSel   => PCMuxSel,
         R7Sel_H    => R7Sel_H,
         RFMuxSel   => RFMuxSel,
         RegWrite   => RegWrite,
         StoreSR    => StoreSR
      );
   I1 : DRAMAuditor
      PORT MAP (
         ADDRESS   => ADDRESS,
         MREAD_L   => MREAD_L,
         MWRITEH_L => MWRITEH_L,
         MWRITEL_L => MWRITEL_L,
         RESET_L   => RESET_L
      );
   theDatapath : Datapath
      PORT MAP (
         ALUMuxSel  => ALUMuxSel,
         ALUop      => ALUop,
         ByteExtSel => ByteExtSel,
         DATAIN     => DATAIN,
         LoadIR     => LoadIR,
         LoadMDR    => LoadMDR,
         LoadMar    => LoadMar,
         LoadNZP    => LoadNZP,
         LoadPC     => LoadPC,
         MARMuxSel  => MARMuxSel,
         MDRMuxSel  => MDRMuxSel,
         PCMuxSel   => PCMuxSel,
         R7Sel_H    => R7Sel_H,
         RESET_L    => RESET_L,
         RFMuxSel   => RFMuxSel,
         RegWrite   => RegWrite,
         StoreSR    => StoreSR,
         clk        => clk,
         ADDRESS    => ADDRESS,
         ADDR_0     => ADDR_0,
         CheckN     => CheckN,
         CheckP     => CheckP,
         CheckZ     => CheckZ,
         DATAOUT    => DATAOUT,
         IMMEDIATE  => IMMEDIATE,
         JSRR       => JSRR,
         Opcode     => Opcode,
         SHIFTop    => SHIFTop,
         n          => n,
         p          => p,
         z          => z
      );
   DRAM : Memory
      PORT MAP (
         ADDRESS   => ADDRESS,
         DATAOUT   => DATAOUT,
         MREAD_L   => MREAD_L,
         MWRITEH_L => MWRITEH_L,
         MWRITEL_L => MWRITEL_L,
         RESET_L   => RESET_L,
         clk       => clk,
         DATAIN    => DATAIN,
         MRESP_H   => MRESP_H
      );

END struct;
