-- VHDL Entity ece411.parseMemCIn2.generatedInstance
--
-- Created:
--          by - bhatia9.UNKNOWN (siebl-0216-13.ews.illinois.edu)
--          at - 21:02:18 12/03/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY parseMemCIn2 IS
   PORT( 
      preMem_C_In2 : IN     lc3b_word;
      is_nop       : OUT    STD_LOGIC
   );

END parseMemCIn2 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF parseMemCIn2 IS 
BEGIN


END generatedInstance;
