-- VHDL Entity ece411.SEXT.generatedInstance
--
-- Created:
--          by - martin43.UNKNOWN (gelib-057-17.ews.illinois.edu)
--          at - 22:20:02 11/03/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY SEXT IS
   PORT( 
      Instr5     : IN     lc3b_imm5;
      Instr9     : IN     lc3b_offset9;
      Instr11    : IN     lc3b_offset11;
      Instr6     : IN     lc3b_index6;
      Imm5       : OUT    LC3b_word;
      PCOffset9  : OUT    LC3b_word;
      PCOffset11 : OUT    LC3b_word;
      Offset6    : OUT    LC3b_word
   );

END SEXT ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF SEXT IS 
BEGIN


END generatedInstance;
