-- VHDL Entity ece411.VHDLsucks.generatedInstance
--
-- Created:
--          by - bhatia9.UNKNOWN (linux4.ews.illinois.edu)
--          at - 16:47:39 12/04/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY VHDLsucks IS
   PORT( 
      count   : IN     std_logic;
      mycount : OUT    std_logic
   );

END VHDLsucks ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF VHDLsucks IS 
BEGIN


END generatedInstance;
