-- VHDL Entity ece411.Way.symbol
--
-- Created:
--          by - bhatia9.UNKNOWN (gelib-057-18.ews.illinois.edu)
--          at - 23:12:58 11/28/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Way IS
   PORT( 
      DataWrite  : IN     std_logic;
      DirtyWrite : IN     std_logic;
      RESET_L    : IN     std_logic;
      WayDataIn  : IN     lc3b_oword;
      index      : IN     lc3b_c_index;
      tag        : IN     lc3b_c_tag;
      DirtyOut   : OUT    std_logic;
      PreHit     : OUT    std_logic;
      TagOut     : OUT    lc3b_c_tag;
      WayDataOut : OUT    lc3b_oword
   );

-- Declarations

END Way ;

--
-- VHDL Architecture ece411.Way.struct
--
-- Created:
--          by - bhatia9.UNKNOWN (gelib-057-18.ews.illinois.edu)
--          at - 23:12:58 11/28/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF Way IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL ValidOut : std_logic;
   SIGNAL match    : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL TagOut_internal : lc3b_c_tag;


   -- Component Declarations
   COMPONENT Compare
   PORT (
      addr_tag : IN     lc3b_c_tag ;
      data_tag : IN     lc3b_c_tag ;
      match    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT DataArray
   PORT (
      DataIn     : IN     lc3b_oword ;
      DataWrite  : IN     std_logic ;
      DirtyWrite : IN     std_logic ;
      Index      : IN     lc3b_c_index ;
      TagIn      : IN     lc3b_c_tag ;
      RESET_L    : IN     std_logic ;
      DataOut    : OUT    lc3b_oword ;
      TagOut     : OUT    lc3b_c_tag ;
      ValidOut   : OUT    std_logic ;
      DirtyOut   : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT myAND
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      O : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Compare USE ENTITY ece411.Compare;
   FOR ALL : DataArray USE ENTITY ece411.DataArray;
   FOR ALL : myAND USE ENTITY ece411.myAND;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   aCompare : Compare
      PORT MAP (
         addr_tag => tag,
         data_tag => TagOut_internal,
         match    => match
      );
   aDataArray : DataArray
      PORT MAP (
         DataIn     => WayDataIn,
         DataWrite  => DataWrite,
         DirtyWrite => DirtyWrite,
         Index      => index,
         TagIn      => tag,
         RESET_L    => RESET_L,
         DataOut    => WayDataOut,
         TagOut     => TagOut_internal,
         ValidOut   => ValidOut,
         DirtyOut   => DirtyOut
      );
   aAND : myAND
      PORT MAP (
         A => match,
         B => ValidOut,
         O => PreHit
      );

   -- Implicit buffered output assignments
   TagOut <= TagOut_internal;

END struct;
