echo "--- Executing initialization force file for ../testcode/5_factorial.asm ---"

echo "Resetting processor for 5 ns."
force /reset_l 0 @0
force /reset_l 1 @5
echo "Initializing the processor."
force /start_h 0 @0
force /start_h 1 @10

-- Test case: lowering start_h should not impact the function of the processor
force /start_h 0 @ 100

echo "Done initializing processor, loading ../testcode/5_factorial.asm program code."
run 5
change /mp2_cpu/dram/vhdl_memory/mem(0) X"13"
change /mp2_cpu/dram/vhdl_memory/mem(1) X"62"
change /mp2_cpu/dram/vhdl_memory/mem(2) X"7F"
change /mp2_cpu/dram/vhdl_memory/mem(3) X"9C"
change /mp2_cpu/dram/vhdl_memory/mem(4) X"81"
change /mp2_cpu/dram/vhdl_memory/mem(5) X"1D"
change /mp2_cpu/dram/vhdl_memory/mem(6) X"14"
change /mp2_cpu/dram/vhdl_memory/mem(7) X"64"
change /mp2_cpu/dram/vhdl_memory/mem(8) X"14"
change /mp2_cpu/dram/vhdl_memory/mem(9) X"6E"
change /mp2_cpu/dram/vhdl_memory/mem(10) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(11) X"16"
change /mp2_cpu/dram/vhdl_memory/mem(12) X"C7"
change /mp2_cpu/dram/vhdl_memory/mem(13) X"16"
change /mp2_cpu/dram/vhdl_memory/mem(14) X"86"
change /mp2_cpu/dram/vhdl_memory/mem(15) X"14"
change /mp2_cpu/dram/vhdl_memory/mem(16) X"07"
change /mp2_cpu/dram/vhdl_memory/mem(17) X"04"
change /mp2_cpu/dram/vhdl_memory/mem(18) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(19) X"18"
change /mp2_cpu/dram/vhdl_memory/mem(20) X"02"
change /mp2_cpu/dram/vhdl_memory/mem(21) X"18"
change /mp2_cpu/dram/vhdl_memory/mem(22) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(23) X"0E"
change /mp2_cpu/dram/vhdl_memory/mem(24) X"06"
change /mp2_cpu/dram/vhdl_memory/mem(25) X"19"
change /mp2_cpu/dram/vhdl_memory/mem(26) X"F7"
change /mp2_cpu/dram/vhdl_memory/mem(27) X"05"
change /mp2_cpu/dram/vhdl_memory/mem(28) X"C3"
change /mp2_cpu/dram/vhdl_memory/mem(29) X"1F"
change /mp2_cpu/dram/vhdl_memory/mem(30) X"FC"
change /mp2_cpu/dram/vhdl_memory/mem(31) X"0F"
change /mp2_cpu/dram/vhdl_memory/mem(32) X"15"
change /mp2_cpu/dram/vhdl_memory/mem(33) X"7E"
change /mp2_cpu/dram/vhdl_memory/mem(34) X"FE"
change /mp2_cpu/dram/vhdl_memory/mem(35) X"0F"
change /mp2_cpu/dram/vhdl_memory/mem(36) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(37) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(38) X"01"
change /mp2_cpu/dram/vhdl_memory/mem(39) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(40) X"05"
change /mp2_cpu/dram/vhdl_memory/mem(41) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(42) X"42"
change /mp2_cpu/dram/vhdl_memory/mem(43) X"00"
run 5
echo "Done loading ../testcode/5_factorial.asm program code."
