echo "--- Executing initialization force file for ../testcode/addforwarding.asm ---"

echo "Resetting processor for 5 ns."
force /reset_l 0 @0
force /reset_l 1 @5
echo "Initializing the processor."
-- force /start_h 0 @0
-- force /start_h 1 @10

force -freeze /mp3_cpu/clk 0 -repeat 50
force -freeze /mp3_cpu/clk 1 25 -repeat 50
-- Test case: lowering start_h should not impact the function of the processor
-- force /start_h 0 @ 100

echo "Done initializing processor, loading ../testcode/addforwarding.asm program code."
run 5
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(0) X"22"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(1) X"12"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(2) X"40"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(3) X"16"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(4) X"40"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(5) X"1A"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(6) X"C0"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(7) X"77"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(8) X"C0"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(9) X"6D"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(10) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(11) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(12) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(13) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(14) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(15) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(16) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(17) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(18) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(19) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(20) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(21) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(22) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(23) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(24) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(25) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(26) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(27) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(28) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(29) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(30) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(31) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(32) X"28"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(33) X"12"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(34) X"40"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(35) X"72"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(36) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(37) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(38) X"40"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(39) X"64"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(40) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(41) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(42) X"60"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(43) X"16"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(44) X"80"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(45) X"68"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(46) X"00"
change /mp3_cpu/mymp3_cache/IPRAM/vhdl_memory/mem(47) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(0) X"22"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(1) X"12"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(2) X"40"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(3) X"16"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(4) X"40"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(5) X"1A"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(6) X"C0"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(7) X"77"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(8) X"C0"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(9) X"6D"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(10) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(11) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(12) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(13) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(14) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(15) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(16) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(17) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(18) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(19) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(20) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(21) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(22) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(23) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(24) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(25) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(26) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(27) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(28) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(29) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(30) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(31) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(32) X"28"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(33) X"12"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(34) X"40"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(35) X"72"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(36) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(37) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(38) X"40"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(39) X"64"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(40) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(41) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(42) X"60"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(43) X"16"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(44) X"80"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(45) X"68"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(46) X"00"
change /mp3_cpu/mymp3_cache/DPRAM/vhdl_memory/mem(47) X"00"
run 5
echo "Done loading ../testcode/addforwarding.asm program code."
